### ISSUE TITLE
Silverwood leaves have gravity

### ISSUE THREAD

**Issue by erima** [Funwayguy/EnviroMine#108]
Thaumcraft Silverwood leaves fall when a connected block is chopped, where normal leaves seem to explode to death when not connected to wood. I actually kind of like it, it scared the crap out of me. Having spent the IRL summer learning how to chop the trees in my yard to bits it makes a lot of sense too.

**Comment by Funwayguy** [comment]
This is likely because either there is no configuration file telling it how to handle the custom leaves. Please use the hotkey to add the block to the configs and refer to the wiki if you need help on how to configure them.
