### ISSUE TITLE
Crash in my own modpack because AUTH-File doesn't work!

### ISSUE THREAD

**Issue by Tomson124** [Funwayguy/EnviroMine#110]
I made a modpack on the TechnicLauncher and I uploaded the ENVIROMINE-AUTH file along with all other config files for the pack. But if I download the modpack it crashes with this error:
`java.lang.SecurityException: UNAUTHORIZED USE OF MOD ENVIROMINE`
But I have downloaded it from your github and in your FAQ it says I'm allowed to include your mod in my pack.
Fast help would be nice, as my pack-downloaders are unable to play the pack.

Tomson

P.S. Sorry for my horrible english at some points, I'm a german student :)

**Comment by thislooksfun** [comment]
If it was working before you uploaded it, then I don't know. I don't see any reason why that shouldn't work...

**Comment by Ac1dSn0w** [comment]
I usually see this error whenever I play offline mode.

**Comment by Funwayguy** [comment]
I know of modpacks using EnviroMine and the AUTH file that work just fine on Technic. I'd double check you have the correct AUTH file for your version and that Technic is installing it correctly.

**Comment by Tomson124** [comment]
How can I check if it installs it correctly?

**Comment by UpcraftLP** [comment]
Wenn du willst schick mir den installationslink und ich schaue ob es bei mit funktioniert ^^

**Comment by Tomson124** [comment]
@UpcraftLP Jetzt zurzeit gehts, hab vorrübergehnd die Enviromine Mod ausm Pack rausgenommen.

**Comment by UpcraftLP** [comment]
@Tomson124 Schick mir einfach mal den Link und ich seh was ich machen kann damit Enviromine auch geht.
PS: Schon irgendwie lustig dass in einem englischen Forum deutsch geschrieben wird ;D

**Comment by Tomson124** [comment]
@UpcraftLP Ja schon lustig :D 
http://technicpack.net/modpack/radioactive-fortress.572345
Wenn du die Version mit Enviromine willst wähl unter Modpack Einstellungen im TechnicLauncher einfach die Version 0.2a aus.

**Comment by UpcraftLP** [comment]
ok ich schau mal woran es liegen könnte...

**Comment by UpcraftLP** [comment]
von der modliste her denke ich es könnte an armorStatusHUD liegen da enviromine oft probleme mit mods hat, die irgendwelche HUDs hinzufügen (Beispiel siehe andere BUG-Reports) aber ich lad es mir mal runter und schaue genauer nach

**Comment by UpcraftLP** [comment]
Also ich hab mir ein paar Crash-Reports angesehen (v0.2a) und hab ein paar Fehler gefunden:

1. Optifine wird von manchen Mods nicht supported, mit OF lässt sich das Pack nicht starten.
2. Nimm die neueste Version von Enviromine (1.3.99).
3. Es scheint an irgendeiner andren Mod zu liegen, teste das einfach mal.

Hier die Crash-Reports für den Fall dass ich was übersehen hab:
1. http://pastebin.com/FDhKhE50    --DEFAULT
2. http://pastebin.com/R0bCVM99   --Ohne OF
3. http://pastebin.com/93XSNvXF    -- AUTH-File gelöscht
4. http://pastebin.com/zMfapAra      -- Neuester Enviromine-Build; kein Crash-Report sondern HS-ERR-PID

**Comment by UpcraftLP** [comment]
@Funwayguy please look over this error message i'm getting the same crash with the newest build and a new auth file.
http://pastebin.com/zMfapAra

**Comment by Funwayguy** [comment]
That last error message is a crash in the Java Runtime and not in Minecraft itself. I've also tested this repeatedly and still cannot reproduce the security crash. Another theory I have is that when you updated EnviroMine on the master copy of the pack you aren't starting it up to authenticate the new version before distributing it.

**Comment by UpcraftLP** [comment]
I installed the Modpack at version 0.2a and I deleted optifine. It resulted in a normal crash report. Then I deleted the auth file and updated the enviromine version to the latest build. When I started the pack I got the jvm crash.

**Comment by Tomson124** [comment]
Optifine cannot be the problem as it worked fine before the enviromine security update.

**Comment by thislooksfun** [comment]
@Tomson124 *_before_*, yes. But after?

**Comment by Grim-Ascensions** [comment]
I've had the AUTH issue when I update the mod in my modpack as well. But its usually because I forgot to generate a new AUTH file for the modpack.

Try:
-Create a backup of Enviromine Configs folder.
-Delete enviromine and all its configs and run the game; make sure you actually load a world. If it crashes, then its not related to the mod.
-Re-add enviromine and run the game; again making sure to load into a world to fully generate configs.
-Overwrite the old AUTH file in your backup with the new one. Then delete the new configs and plug your backup back in.

FYI: The generated config file changed a few versions ago. If you haven't updated to the newer config, that "may" be causing an issue. Not sure though.

**Comment by Tomson124** [comment]
Thanks @Grim-Ascensions that fixed it.
I deleted it and let it generate a new one, and now it works again.
Thnaks man.
