### ISSUE TITLE
Player jitters in DIM 0

### ISSUE THREAD

**Issue by erima** [Funwayguy/EnviroMine#111]
*I opened this issue over on EnviroMine/EnviroMine-1.7 and just realized that I'm not sure which repo is the one to leave things like this on.*

After updating to 1.3.99 the player suddenly jitters uncontrollably. I'm not exactly sure what triggered it. I was spending most of the time in a Mystcraft world, and there were some gravel/dirt cave-ins that hit me. Leaving the world for DIM 0 I started shaking like I was falling through a block but then going back up. Going into other dimensions seems to stop it, but it starts again upon return. Removing Enviromine entirely stops the behavior.

I'd check against the previous version but it's now telling me that I'm not using a registered mod and crashes.

**Comment by thislooksfun** [comment]
1.7 is the right place for the issue.
