### ISSUE TITLE
[Bug] Invisible collisions after breaking Burning Coal || container.freezer visual || Authorization crash in offline mode

### ISSUE THREAD

**Issue by Ac1dSn0w** [Funwayguy/EnviroMine#113]
1. No preview of such. But if a user plays with burning coal. You'll notice the collision issues.

2. 'Container.Freezer' needs to be fixed to 'Freezer'

3. Authorization causes game crash in offline mode after updating Enviromine from a previous version.

**Comment by thislooksfun** [comment]
1. We'll look into that.
2. Oops. That's an easy fix though, and isn't super important.
3. This however, is important. Looks like we missed that check. Our bad.

**Comment by GenDeathrow** [comment]
I have 2 fixed so far will be in next update

**Comment by GenDeathrow** [comment]
# 2 in build .101
