### ISSUE TITLE
[Suggestion] Flowing Rivers mod water drinkability

### ISSUE THREAD

**Issue by Ac1dSn0w** [Funwayguy/EnviroMine#114]
I notice if using EnviroMine, can't drink flowing river water.

Screenshot: http://i.imgur.com/SaTJ026.jpg

Real Flowing Rivers (Streams) Mod: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2346379-streams-real-flowing-rivers

Edit: My bad. Forgot to add the mod I'm using on EnviroMine

**Comment by medsal15** [comment]
From the "Streams" mod?

**Comment by GenDeathrow** [comment]
Sorry make sure to post on the 1.7 version and not 1.6 issues trackers.  We don't look at this much. But I'll see what's happening on this.

**Comment by GenDeathrow** [comment]
I believe this is already been fixed in one of the newest updates
