### ISSUE TITLE
Grues attack outside Cave Dimension on Fri 13th

### ISSUE THREAD

**Issue by Psithief** [Funwayguy/EnviroMine#116]
Seems like an oversight. Cave Dimension isn't even enabled on my game.

No "pitch black" achievement (didn't have prerequisite either), no messages, just blindness, then death.
No death message after the fact either.

**Comment by Psithief** [comment]
https://github.com/EnviroMine/EnviroMine-1.7/blob/master/src/main/java/enviromine/handlers/HandlingTheThing.java

```java

if((EM_Settings.disableThing && !flag) && player.dimension != EM_Settings.caveDimID || player.worldObj.difficultySetting == EnumDifficulty.PEACEFUL)
```

I think this is meant to be `|| player.dimension != EM_Settings.caveDimID`.

**Comment by Funwayguy** [comment]
No that line is fine-ish. Just a missing set of brackets is messing up the order of operations (/_-)

**Comment by Psithief** [comment]
:stuck_out_tongue: That's exactly the same logic.

I'll be playing on Peaceful for the rest of the day, since grues are inappropriate in the ever-bright Nether.

**Comment by twothe** [comment]
Yeah basically if you play on Friday 13th with EnrivoMine you basically can't play Minecraft. -.-

**Comment by GenDeathrow** [comment]
Not true, it work as intended for the most part. A couple of little things just needed to be tweaked. So players should only be attacked under certain circumstances. Which @Funwayguy has already been working on. This was the first real run with the Friday the 13th. There are always bound to be issues the first time something is ran.

**Comment by Funwayguy** [comment]
This should be fixed now

**Comment by Psithief** [comment]
Great!
Now, my curiosity wants to know why there's a "messages" static. Is that referenced from elsewhere or is  it just dead code?

**Comment by Funwayguy** [comment]
Where do you see this @Psithief?

**Comment by Psithief** [comment]
Same file. Doesn't seem used, but could just be I missed something.

```java
static
	{
		messages.add("Stay in the light!");
		messages.add("It's too dark...");
		messages.add("ESCAPE!");
		messages.add("...never safe...");
		messages.add("Where did they go...");
		messages.add("NOT INSANE... NOT INSANE...");
		messages.add("help... me...");
		messages.add("I hear it coming...");
		messages.add("...why can't they hear me...");
		messages.add("So alone...");
		messages.add("HELP!");
		messages.add("...can't hide...");
		messages.add("Run!");
		messages.add("Why me?");
	}
```

**Comment by twothe** [comment]
Yes it works as intended for the most part, except for that part where you die all 15 minutes on Friday 13th with so much damage that your armor gets destroyed no matter where you are or what you do.

Seriously: if you put in easter eggs at least test them! I had a lot of very angry players on my server yesterday.

**Comment by Funwayguy** [comment]
Well the grue has actually been in the mod for over 6 months now and they were assumed working at the time. I didn't expect them to even work outside the caves let alone attack. And the messages were a side feature that was never finished... probably will stay that way for now

**Comment by Psithief** [comment]
> Seriously: if you put in easter eggs at least test them! I had a lot of very angry players on my server yesterday.

Yeah, you'd be getting more complaints if most people knew what the problem actually was.
Easter Eggs that can't be disabled are a terrible idea in practice. There have been many disastrous mods that simply crash servers entirely (or worse) on Halloween or Christmas.
