### ISSUE TITLE
Crash after loading Enviromine with Smart Moving ->Render Player API

### ISSUE THREAD

**Issue by Hague** [Funwayguy/EnviroMine#118]
I get a crash upon loading a fresh SSP world:

http://pastebin.com/zrgGuuV9

It appears that some information cannot be cast properly in the context of a modified enviromine model.

**Comment by GenDeathrow** [comment]
This is a known issue I am working on fixing at the moment. 

For now I main config file, turn 3d render gear off. I will try to get a hot fix in the next few hours.   

Direct to our 1.7 issue tracker here. 

https://github.com/EnviroMine/EnviroMine-1.7/issues/99
