### ISSUE TITLE
Server Not loading.

### ISSUE THREAD

**Issue by NeturonicAngelz** [Funwayguy/EnviroMine#119]
Updated from .03 to .04 and the following error now appears for server loading of the Mod:
- http://pastebin.com/42f12js8

Hope you can fix it up, thanks!

**Comment by GenDeathrow** [comment]
Should be an easy fix.  Sorry for the inconvenience. We will get to hopefully next day or so.

**Comment by NeturonicAngelz** [comment]
Haha, don't be sorry, ;p It's completely fine, at least you have amazing people to get these issues out there for you ;p

**Comment by GenDeathrow** [comment]
Build 105 should hopefully fix server issue.

**Comment by NeturonicAngelz** [comment]
Confirmed it does fix it. Thank you very much Gen,
Also, if you haven't already this is the Modpack which
I own which includes your Enviromine mod (With Author Links and such)
http://www.technicpack.net/modpack/destouniverse.589456

**Comment by GenDeathrow** [comment]
Cool I'll have to check it out. There is a known issue with filling water bottles not filling correctly. Funwayguy was going to take a look at it
