### ISSUE TITLE
Cannot Hotload Dim: Overworld is not Loaded!

### ISSUE THREAD

**Issue by PigheadedGnu** [Funwayguy/EnviroMine#120]
Minecraft crashed with the following (while I was in the dimension created by the Atum Mod):

https://gist.github.com/PigheadedGnu/dcd932b97c2e5f9b2044

I'm happy to try isolating it more if you think it's an interaction with more than one mod (but a quick look at the traceback makes me think it's a general dimension related issue).

**Comment by PigheadedGnu** [comment]
Sorry, probably not Enviromine... Sorry! https://github.com/micdoodle8/Galacticraft/issues/1355

**Comment by GenDeathrow** [comment]
It may not be enviromine. But did you try to turn off gasses in our config?  And what mods do you have?

**Comment by PigheadedGnu** [comment]
The mods are listed in the stack trace (there are alot). I got a similar error after removing Enviromine completely and then found that Galacticraft issue that points towards the TooMuchTime mod having an issue. I removed that mod and the issue has not re-occurred.

Thanks for a great mod!

**Comment by GenDeathrow** [comment]
Thank you!
