### ISSUE TITLE
[Mod Compatibility] Terrafirmacraft body temp code hooks

### ISSUE THREAD

**Issue by Balthizar** [Funwayguy/EnviroMine#126]
I am writing this as I found no similar post listed here. 

I use this mod in conjunction with another which is called Terrafirmacraft. Terrafirmacraft provides code hooks for collecting the biome temperature, body temperature etc from their mod for use in other mods such as this one. I was wondering if you would be able to create a small patch which ties your mod's effects for body temp straight into the values provided by terrafirmacraft? This would allow me to use not only the air quality but also the body temperature features along side terrafirmacraft itself which lacks such game mechanics yet.

**Comment by thislooksfun** [comment]
This has already been answered here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293048-enviromine-a-little-bit-of-realism-new-physics?comment=2369
