### ISSUE TITLE
no auth file 

### ISSUE THREAD

**Issue by Dr-gummybears** [Funwayguy/EnviroMine#127]
help! i installed enviromine for my privet use and i don't have the auth file and every time i try to play it enviromine makes my game crash how do i get the auth file

**Comment by Funwayguy** [comment]
Which version are you using?

**Comment by Dr-gummybears** [comment]
1.3.110 and using multimc

**Comment by Funwayguy** [comment]
1.3.110 doesn't have any Authentication code running... I don't even know how this happens. 1.3.111 might work better because all traces of authentication has been wiped out.

**Comment by Dr-gummybears** [comment]
But every time I load enviro mine it says required auth file not found then I click ok and then it crashes so ok thanks I will try 1.3.111 thanks for your help 

DR gummybears

**Comment by thislooksfun** [comment]
If you still have one of the crash logs, could you post it please?
