### ISSUE TITLE
Camel Pack dont`n filled

### ISSUE THREAD

**Issue by Tsyklop** [Funwayguy/EnviroMine#129]
Enviro mine 1.3.113
![2015-04-19_09 13 48](https://cloud.githubusercontent.com/assets/6783568/7218440/037e573c-e678-11e4-9afe-2c9197aae2fb.png)

**Comment by Tsyklop** [comment]
In survival mode is the same

**Comment by UpcraftLP** [comment]
Maybe cooking the water would help?

**Comment by Tsyklop** [comment]
@UpcraftLP This water and cooked in the furnace so

**Comment by thislooksfun** [comment]
Could you install the mod NBTReader, place the camel pack that isn't working into the "NBT Reader" block, and send me a screenshot of the GUI?

**Comment by Tsyklop** [comment]
@thislooksfun OK.

**Comment by thislooksfun** [comment]
Huh. That's odd. The NBT data looks normal... Maybe @funwayguy knows.

**Comment by Tsyklop** [comment]
And Camel pack dont`t filled if install only EnviroMine

**Comment by Funwayguy** [comment]
Just looked at the code and I changed the fill value for bottles and they are now in configs instead of being hard coded. Check you minecraft.cfg file for the water bottle item configs and check what the camel pack fill value is there.

**Comment by Tsyklop** [comment]
@Funwayguy I do not have a file minecraft.cfg

**Comment by nicolas255** [comment]
Hi,

Any news about this ? Because it's making the update... a little problematic... :/

**Comment by Funwayguy** [comment]
I might just revert the change...

**Comment by joshthegrate** [comment]
i too can not fill a camel pack with water bottles.

**Comment by joshthegrate** [comment]
discovered the cause of this bug. it is incompatibility issues with forge essentials

**Comment by jordanhayes1990** [comment]
i found the problem in the mincraft.cfg go down towards the bottom and there is water bottle and potion bottle on the water bottle change the camel pack fill value to 25 not -25 then it will work on servers. before this change it would only work on single player

**Comment by jordanhayes1990** [comment]
the minecraft.cfg is in the config>enviromine>profiles>default>custompropoties> then minecraft.cfg

and its line 1926                I:"12.CamelPack Fill Amount"=-25

change it to                       I:"12.CamelPack Fill Amount"=25

**Comment by MoofMonkey** [comment]
123
