### ISSUE TITLE
Support for HUDWidgets

### ISSUE THREAD

**Issue by Flenix** [Funwayguy/EnviroMine#132]
Hello.

Just a quick one really; couldn't find anywhere else to contact.
Is there a deobfuscated/API copy readily available anywhere? I run a small mod called HUDWidgets which allows users to customize the way all aspects of the HUD are displayed and it'd be cool to add the stats from this to that mod, so things will remain uniform for my users when using your mod.

Thanks :)

**Comment by Funwayguy** [comment]
You can find the deobfuscated jar here:
https://drone.io/github.com/Funwayguy/EnviroMine-1.7/files

Please note that we are in the process of rewriting the mod so things will change significantly when we're done.

**Comment by GenDeathrow** [comment]
They are registered in the Clint proxy.
