### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by lightning02** [Funwayguy/EnviroMine#134]
(tlf) EDIT: Moved crash log [here](https://gist.github.com/thislooksfun/40279afd8122df589fdf)

**Comment by thislooksfun** [comment]
A couple things:
1. Please use [pastebin](pastebin.com), [gist](gist.github.com) or some similar website in the future. Thanks.
2. You're gonna have to provide more information than that. "It crashed" is not enough for us to be able to magically fix it. What were you doing when it happened? Has it happened before? Did you install a new mod recently that is conflicting? We need to know these things to be able to help you.

**Comment by lightning02** [comment]
Oh.. i'm sorry for posting in this way. 
The problem occurse when "attempting to generate world".
I don't really know if there is another mod conflicting, it could be, but the problem occurred when I used to add "Enviromine" too inside.
If you need i can provide you some logs.

**Comment by GenDeathrow** [comment]
I dont see anything enviromine causing issues from the crash log, Im not saying that enviromine isn't conflicting, but that log doesn't really show whats going. Id leave enviromine.. and slowly remove other mods one by one.. find which one its conflicting with.
