### ISSUE TITLE
Failing to load custom config file

### ISSUE THREAD

**Issue by Forecaster** [Funwayguy/EnviroMine#136]
Error:
http://hastebin.com/ihehikagan.avrasm

The file that is failing to load:
http://hastebin.com/ijejifudan.avrasm

My stability types:
http://hastebin.com/zohepacofa.coffee

The problem is it doesn't specify why it's failing.

Earlier I had changed the names of my stability types, it then said it couldn't find a stability type with the name "basic_support", which I had changed to "basic-support", although I changed them in the block configs as well, or so I thought.

I then changed it back to "basic_support" (and the other names to use _ as well) everywhere and now it's giving me the NPE with no reason again. And I have no idea why.

Also, this is on my server. It worked fine in single player.

**Comment by thislooksfun** [comment]
Can you post the full log? Not just the crash?

**Comment by Forecaster** [comment]
It's not a crash.

The server starts fine. It just doesn't load that file.

**Comment by Forecaster** [comment]
Figured it out.
There was an old file called MyCustom.cfg amongst the mod files. It had a duplicate of one of the artifice blocks. Presumably it failed when trying to load a block it had already loaded.

Removing MyCustom.cfg allowed it to load properly once again!

**Comment by thislooksfun** [comment]
That probably still shouldn't be happening though...

**Comment by GenDeathrow** [comment]
When I did the config conversions I left the "My Config" file because if players had custom files already it was easier than trying to convert the file over. The npe errors shouldn't have happened I will look at it.  Thanks for posting this.

**Comment by Forecaster** [comment]
MyCustom.cfg: http://hastebin.com/isuxowipin.coffee
Artifice.cfg: http://hastebin.com/uqivogajam.coffee

They both have an entry with the name "tile_artifice_frame".

I suspect the npe happened when it got to "Artifice.cfg" as it had already loaded one "tile_artifice_frame".

**Comment by GenDeathrow** [comment]
will close this issue as I believe this is already been fixed
