### ISSUE TITLE
Termperature is not reset after death?

### ISSUE THREAD

**Issue by Usverin** [Funwayguy/EnviroMine#137]
When i have died by burning, termeprature is not reset. Is this correct?

Global_Settings.cfg
...
    B:"Keep statuses on death"=false
...

**Comment by joshthegrate** [comment]
are you using cauldron or forge? because i have this same issue with cauldron.

**Comment by joshthegrate** [comment]
As a temp solution is there a command that will reset a players stats that I can put in a command block?

**Comment by thislooksfun** [comment]
There is not... We never added @ selectors to the commands, so there isn't a way at the moment. Sorry.

**Comment by GenDeathrow** [comment]
I am looking to add in @ selectors commands with the next update..

**Comment by PitchBright** [comment]
I just changed my server and client config to
    B:"Keep statuses on death"=true

And that seemed to fix this bug, although I haven't tested it extensively.

Could it be that you have this worded incorrectly in the description in the config, GenDeathrow?

**Comment by GenDeathrow** [comment]
Possibly but funwayguy I think added it in. I am slowly doing some more bug fixes.. and ill double check this.
