### ISSUE TITLE
Physics Questions

### ISSUE THREAD

**Issue by WolfieWaffle** [Funwayguy/EnviroMine#141]
I'm trying to configure the physics system so that leaves can hang like stalactites or vines, but even settiing canHang: to true does not work. I also had a few other questions that I could not find answers to on the wiki, for example:

- What does he min/max missing do?
- What does canHoldOthersUp do?

Sorry if these were answered somewhere else, I've been looking for quite a while and couldn't find anything.

**Comment by GenDeathrow** [comment]
We should have them in the wiki.
