### ISSUE TITLE
Walking on Slabs

### ISSUE THREAD

**Issue by Echo343** [Funwayguy/EnviroMine#144]
Walking on slabs causes Sanity to drop fairly quickly.

**Comment by Echo343** [comment]
I'm using version 1.3.118 for Minecraft 1.7.10

**Comment by GenDeathrow** [comment]
You probably have something set in your custom configs that's doing this.. its not a mod issue.  I cant reproduce it, and we don't have any blocks hard-coded anymore really. unless you can provide more information on this.. their isn't any way we can help.
