### ISSUE TITLE
Generation of Mines Making Server Startup Incredibly Slow(or preventing it)

### ISSUE THREAD

**Issue by Omuck3** [Funwayguy/EnviroMine#145]
Hi.  This has never caused a problem before, but now the server(making a new world), generates some mines fine, then generates gases, then generates more mines so slowly...

I turned off all mine generation AND generated structures...

**Comment by KuroNeko87** [comment]
I hope this helps the devs find the Issue. For what i can see, the error is super random, and it depends on the location of where you'respawning, the biomes and anything else in the area.

https://gist.github.com/KuroNeko87/ec9a2aad703a3a8760e0

**Comment by GenDeathrow** [comment]
This was fixed with latest update.. it will still recursively generate, but you can actually shut if off now.  I am not sure but I was told it could be forge essentials or tools.. something like that. either way the configs work to shut it off.
