### ISSUE TITLE
Idea for insanity suggestion

### ISSUE THREAD

**Issue by skuma01** [Funwayguy/EnviroMine#146]
HEY!
So i thought that a good idea for insanity is that the farther you are away from your spawn, the more insane you get? Good idea or not?

**Comment by SirSquidly** [comment]
I think this seems a little unfair, forcing players to stay in one spot, and disallowing exploration, one of the points of the game. This would also make resources eventually harder to obtain, as everyone will have to share in the same spot. 

So, I think this is a bad idea.

**Comment by GenDeathrow** [comment]
As for now. This would make sanity harder than it already is.. sanity needs to be balanced more as it is. Recently messing around with sanity we have too many negatives and not enough positives.
