### ISSUE TITLE
Sanity on a no-sleep server

### ISSUE THREAD

**Issue by Nocty201** [Funwayguy/EnviroMine#147]
Hi,

On the server we're running, sleep is disabled and beds only set the respawn point. We're using a much longer day/night cycle (2h/40m last map) as well. Sanity seems to be a real issue, as sleeping is the only effective way I've found so far to raise sanity once you've gone long enough without sleep (?). Was wondering if you had suggestions on how to deal with such a config (we  would love to keep the sanity mechanic) without the ability to sleep, or if there's a config option I've overlooked to help? 

Thanks!

**Comment by GenDeathrow** [comment]
closing this one.. since we have a dup
