### ISSUE TITLE
Add support for gas masks

### ISSUE THREAD

**Issue by LemADEC** [Funwayguy/EnviroMine#15]
Mekanism adds a Gas mask: I would love to see it consume energy when I'm mining and protect from lack oxygen

GasCraft adds a Gas mask: it has no fuel so I would expect to see it reduce the effect of lack of oxygen without compensating it

Both of those goes in helmet place so I guess their would be easy to add support for it ?

**Comment by Funwayguy** [comment]
I'm going to close this issue now that EnviroMine has it's own mask
