### ISSUE TITLE
Issue when dead

### ISSUE THREAD

**Issue by MightyElemental** [Funwayguy/EnviroMine#151]
I died and it prevented me from respawning or going to menu. It also said this:

[13/8/2015 19:05:43 PM] [WARNING] [EnviroMine] Unable to get EnviroTracker for GUI!
[13/8/2015 19:05:43 PM] [WARNING] [EnviroMine] Please report this to the mod developers!

This is the reason why I dont use this mod ;(

**Comment by GenDeathrow** [comment]
More than likely, another mod(what mods u have installed?) is erasing players data.. What version are you using? Make sure your u pto date. Cause I think I had removed those debugging printouts? Enviromine plays pretty nice with a lot of mods, except a select few.  I can understand your frustration, but we can only fix issues when they are told to us.

**Comment by GenDeathrow** [comment]
Im closing this topic unless you have anything else to add to help solve the issue.

**Comment by MightyElemental** [comment]
Yeah sorry. I have a ton of mods installed and it would take forever to list them. But I'm using MC 1.6.4

**Comment by GenDeathrow** [comment]
1.6.4 was discontinued over a year 1/2 ago now.. it was riddled with bugs that were fixed in 1.7.10.. 1.7.10 became a much more stable version.

**Comment by MightyElemental** [comment]
I understand this, but some of the mods I use are 1.6.4 only.

**Comment by GenDeathrow** [comment]
Well I know alot of good mods died in 1.6.4.. im sure there are quite a few mods in 1.6 that aren't updated anymore.  We dont have the resources to spread out over mutiple versions. Now if you have 1.7.10 issue I would gladly go it on the next update.  I try to fix issues when I can. I wish I was able to help.

**Comment by MightyElemental** [comment]
Ok, thanks for being a good admin. ;)
