### ISSUE TITLE
Animal Lover mode option

### ISSUE THREAD

**Issue by TweakerTheBarbarian** [Funwayguy/EnviroMine#152]
I'm really enjoying EnviroMine, anything to make MC harder and more complex is fun. Here's an idea that popped into my head while reading about the Vegan Option mod.

Attacking, killing or eating passive, or non-aggroed neutral mobs degrades your sanity.

This might be a fun companion feature to Vegan Option with replaces mob drops with vegan alternatives.

**Comment by SirSquidly** [comment]
This doesn't sound that good of an idea, just because of how it seems biased towards non vegans, but will make a great settable option in configs! I'm opening a suggestion for this.

**Comment by TweakerTheBarbarian** [comment]
A config option (off by default) would be great!

**Comment by Funwayguy** [comment]
Because this can pretty much be done through custom configs and is based on personal opinions/beliefs, no.
