### ISSUE TITLE
Suggestion: Sanity on Kill

### ISSUE THREAD

**Issue by SirSquidly** [Funwayguy/EnviroMine#155]
The idea of this is to effect sanity on kill of a mob, as an option in the config. This could lead to some interesting things, such as killing the Ender Dragon/Wither improves your sanity amazingly, cause it fills the player with accomplishment.  OR, killing other players lowers sanity, making them into psychos if they are murderers.

I would love to see this in new versions of enviromine, as it makes a whole new dynamic to gameplay, providing a more interesting experience.

**Comment by GenDeathrow** [comment]
Love the idea.. I want to make a modification to sanity to work more like call of cthullu pnp.. harsh but somewhat stable..  they have that mechanic in it.. killing a monster can return sanity.

**Comment by GenDeathrow** [comment]
Just added this in.
