### ISSUE TITLE
Enviromine Torches are not taking the place of Vanilla Torches

### ISSUE THREAD

**Issue by Kucan** [Funwayguy/EnviroMine#156]
Going from what I know of the mod, usually, when a torch is placed, enviromine switches it with one of it's own and that torch can ingite blocks around it and can go out. However, when a vanilla torch is placed, it stay vanilla and has no additional features.

Even if you place an Enviromine torch from creative down and mine that, you'll get a vanilla torch back.

I'm using version 1.3.121.

**Comment by GenDeathrow** [comment]
Great... well tried to tackle this last update.. but originally wasn't my code.. I must have missed something.  Ill look at it again when I get a chance... and we all have a lot of projects going on.

**Comment by GenDeathrow** [comment]
This should be fixed.. I had something committed out when I posted that last version that should have not been. So it should be working now
