### ISSUE TITLE
Request Information - GenDeathrow

### ISSUE THREAD

**Issue by DPxKnightxZero** [Funwayguy/EnviroMine#159]
Did you take over funways mods? If so can you please update his other mod infiniteinventory to allow the proper use of inventory tweaks? Also if you can do that can you update and fix inventory tweaks the dev has not made a real fixed 1.7.10 update since april.

**Comment by GenDeathrow** [comment]
I did not take over funwayguys mods. I am part ofthe enviromine team. Funwayguy has RL stuff going on with college.  I am trying to keep enviromine uptodate uu ntill we get the rewrite done.. he has been work in on it in his spare time. But he has alot of projects going on.
