### ISSUE TITLE
Stability..

### ISSUE THREAD

**Issue by zHawky** [Funwayguy/EnviroMine#170]
Ehm, about stability - idk how as it considered - feature or bug. Yesterday im tested EnderIO and Thermal Expansion blocks.
When blocks from TE falling it have no loss energy, when EnderIO falling they loss all energy, even exp obelisk wipe my 41 exp :( 
That happen because EnderIO are newer or just not implemented in enviromine?

Edit: briefly - please make config for disabling physics in certain mods, eg vanilla blocks should have physics and Thaumcraft with EnderIO none.

**Comment by zHawky** [comment]
Close issue because it looks pretty dumb for me and everyone.

**Comment by GenDeathrow** [comment]
Well I havent had a check to look into this.. not sure what ender io is doing, but when I do get the chance it will get looked at
