### ISSUE TITLE
[Question]   Gas in existing world?

### ISSUE THREAD

**Issue by rob-bb** [Funwayguy/EnviroMine#174]
Hi.  There is a setting for generation gasses, what happens in existing chunks?  I have a world pregenerated so was wondering if the gas would be non-existent?

**Comment by GenDeathrow** [comment]
Hey we dont check  this page very often as this is enviromine 1.6.4 version thats obsolete. better to send them here. https://github.com/EnviroMine/EnviroMine-1.7/issues But they just get errased... but you will have pockets of empty spaces underground were the gas was at

**Comment by rob-bb** [comment]
I wondered why there were 2 enviromines on github.  I ended up regenerating the world anyway
