### ISSUE TITLE
Incompatibility with Witchery

### ISSUE THREAD

**Issue by Ravin890** [Funwayguy/EnviroMine#182]
Its not a full blown one, its just that if you get the status effect Dehydration wood starts to randomly spawn on you (most of the time its witchery woods, but sometimes there are vanilla ones)

**Comment by GenDeathrow** [comment]
In config you need the change dehydration potion id

**Comment by Ravin890** [comment]
I found what the effect in that slot was. It was sprouting, well thanks for the help
