### ISSUE TITLE
Issue with enviromine versus rotarycraft liquid pipe with water in it

### ISSUE THREAD

**Issue by OmegaCenti** [Funwayguy/EnviroMine#184]
https://gist.github.com/OmegaCenti/bad0288a693c985b7311

**Comment by OmegaCenti** [comment]
complete crash remote server

**Comment by GenDeathrow** [comment]
All that's showing is a crash because of rotary craft.. only thing I can guess is its a physics issue?  If that's the case set that block to  ?  Ignore physics.. but that needs more info.

**Comment by OmegaCenti** [comment]
Gendeathrow, Tile Entities cannot be excluded from physics.

**Comment by Funwayguy** [comment]
You do know tile entities are bound blocks right? Exempt the block and you exempt the tile.

**Comment by OmegaCenti** [comment]
I should have said Haggle1996 said "Tile Entities cannot be excluded from physics." @Funwayguy, I don't know what a bound block is, however I am currently reading through http://minecraft.gamepedia.com/Block_entity to try and find "bound block" as querying google with "minecraft bound block" is not returning anything. I will search through enviromine next for the term bound block, maybe it is defined in enviromine.

**Comment by OmegaCenti** [comment]
Ive done a search through the code for bound block, didn't get any returns, also did a rudimentary search for bound block in the wiki, and I am getting no hits

**Comment by OmegaCenti** [comment]
I searched here as well: http://minecraft.gamepedia.com/Entity

**Comment by GenDeathrow** [comment]
What funwayguy means is that the tile entity is bound to a block. So a
chest tile entity is bound to a chest block.. they are two separet objects
but the same block. You will have to look at minecraft code to see it..
bound is not an actual object in the code.
