### ISSUE TITLE
Suggestion: Make non-ambient light levels keep player warm in cold biomes also a armor piece

### ISSUE THREAD

**Issue by nanakisan** [Funwayguy/EnviroMine#52]
A daunting request i assume. But i've found that the hot/cold system lacks some ease. You are either hot or you're either cold depending on the biome. Then relying heavily on torches, fire, lava to keep warm in the cold. However i feel like light level should also play on keeping you warm. A properly well lit area should keep a player just warm enough to stop the decline of the cold biomes chill. However this should only apply when the skylight is not affecting the light levels of the player.  
  
Also could you add maybe a Inuits Parka
Example: http://firstpeoplesofcanada.com/images/firstnations/teachers_guide/inuit/clothing_parka_squirrel.jpg

You have the camel pack for deserts. Maybe a personal mod item for the cold biomes.

**Comment by Funwayguy** [comment]
Moved suggestion to https://github.com/EnviroMine/EnviroMine-1.7/issues/73 (mostly because I don't check here and forget about this)

**Comment by 710583** [comment]
Replace the middle of each recipe and put the corresponding leather armour possibly.
