### ISSUE TITLE
suggestions: Stability types and gravity stopping block

### ISSUE THREAD

**Issue by skaviouz** [Funwayguy/EnviroMine#56]
So I have two ideas...

# idea 1: add some more info to defaults
add stability types:

floater (i.e. could be used for angel blocks, slimey dirt, glowstone, clouds)
```
floater {
    B:"01.Enable Physics"=false
    I:"02.Max Support Distance"=12
    I:"03.Min Missing Blocks To Fall"=22
    I:"04.Max Missing Blocks To Fall"=25
    B:"05.Can Hang"=true
    B:"06.Holds Others Up"=true
}
```
structural (i.e. metals/diamond block/steel frames/more modded items from modpack makers adding them for usage with custom files)
```
structural {
    B:"01.Enable Physics"=true
    I:"02.Max Support Distance"=6
    I:"03.Min Missing Blocks To Fall"=22
    I:"04.Max Missing Blocks To Fall"=25
    B:"05.Can Hang"=true
    B:"06.Holds Others Up"=true
}

```

# idea 2: the difficult idea ofc...
I also think you should make a block that exempts other blocks within (10-20? down/n/e/s/w) blocks from being effected from physics (atleast the physics caused from your mod), would be a gravity stopping block if you will... Maybe make it out of netherstar surrounded by wool or string? or a netherstar surrounded by clouds?
You could also just make another option for StabilityTypes, that allows thicker/distance for "holds others up", like
```
B:"07.GravityReducerField"=true
I:"08.Field Deepness"=3
I:"09.Field Horizontalness"=3
```
Don't get me wrong, I suck at coming up with names... but I think this would have a use if this was possible to implement.

Hope you like idea number 2, because it would be cool -- the major reason for this would be for archimidie's ship mod, but if you add the floater blocks to "exempt" you would just have to make the floor of the ship out of floaters, but I think this last option would make adding special permissions for blocks easier, and making floating islands easier.

side thought: you should add more defaults for gaining sanity. Thanks for reading

**Comment by Funwayguy** [comment]
I finally got around to making that 2nd idea in the latest release however it's not craftable.
