### ISSUE TITLE
Default Armor Configs can get generated, even if redundant

### ISSUE THREAD

**Issue by delax** [Funwayguy/EnviroMine#59]
There are two options for enviromine to generate default files, one for vanilla items and another for all armor.
Problem is that the default armor configs apparently are generated even if there already exists configs for the armor.
Sounded like from the wiki/docs that it would take existing configs into account...

This is not an enormous issue (as can be disabled from enviromine.cfg), but certainly an annoying one; as this means by default there will be new conflicting configs each time MC launches or at the very least a redundant mess of them.
Even just with vanilla + enviromine, it will generate 2 different configs for the vanilla armor.

If it matters, currently using v1.2.28 for MC1.7.10

**Comment by Funwayguy** [comment]
New EnviroMine has this as a global option. Closing thread...
