### ISSUE TITLE
Could there be an option for a block to not drop anything?

### ISSUE THREAD

**Issue by delax** [Funwayguy/EnviroMine#70]
Like to make glass or ice shatter when stressed, or as a work-around for weird NBT/Meta-data blocks (ex Railcraft stairs).

I could configure this to happen (in 1.2.28) by telling it to drop a non-block (like an item, or for consistency's sake a simple "null").
Pretty sure this is hacky, so could there be a formalized option?

**Comment by Funwayguy** [comment]
Closing old thread. Blocks dropping nothing should be possible in the newer versions of EnviroMine with correct custom configs.
