### ISSUE TITLE
Mod Conflict - Better Storage

### ISSUE THREAD

**Issue by vkruchev** [Funwayguy/EnviroMine#77]
In the update 1.3.31 of EnviroMine, if used in conjunction with Better Storage, the Better Storage Backpacks would not render an icon and simply displayed the fire icon. In the default creative search function, upon searching for "backpack" the game crashed. After testing for mod conflicts, it was resolved that the conflict was between EnviroMine and Better Storage.

Since then, I have updated EnviroMine to the current version (1.3.38). In the current version, the backpack now has no icon in the GUI but does not crash the game. The backpack can enter a player's inventory and be used, it is also visible on back and on ground. It is simply not visible in the inventory GUI, but when hovering over the item location, the Nameplate information shows up stating the name and flavor text, but the item itself is not visible.

Do you have any advice on how to fix this? Thank you for all of your assistance!

**Comment by Funwayguy** [comment]
Pretty sure this was fixed long ago. Closing...
