### ISSUE TITLE
Crash with Galacticraft

### ISSUE THREAD

**Issue by aik88** [Funwayguy/EnviroMine#93]
Hi, my game crashed if i try to land on an Planet or Moon from Galacticraft. Dont know if the problem on EnviroMine or Glacticraft Side. I hope u can help me fix the problem.

EnviroMine 1.3.65
Galacticraft 3.0.6.248

Log:
http://pastebin.com/Fh2D4UrB

**Comment by Funwayguy** [comment]
Is this issue still present? If so can this be moved to the 1.7.10 thread?
