### ISSUE TITLE
Scaled bars rendered wrong

### ISSUE THREAD

**Issue by DirkSch** [Funwayguy/EnviroMine#96]
I have scale the bars by 0.80 and only the first top bar ist scaled by 0.80. all other bars scaled on the previous bar. it's the version EnviroMine-v1.3.80 installed on the Project RETv7 modpack. on techniklauncher. 
Its look like so: https://dl.dropboxusercontent.com/u/3567768/envirominebug.png

**Comment by thislooksfun** [comment]
Whoops..... Hey @GenDeathrow, got a bug for you.

**Comment by GenDeathrow** [comment]
This should have been fixed already. Thought I had already responded to this message.
