### ISSUE TITLE
Thaumcraft chestplates rendering problem.

### ISSUE THREAD

**Issue by wiiv** [Funwayguy/EnviroMine#99]
When I add enviromine, some of thaumcraft chestplates and ic2 have some problem rendering, some of them disappear, others get a weird brown tint. Can you check this? I can post some screenshots if needed.

**Comment by thislooksfun** [comment]
What chestplates do this? Can you give us the name(s)?

**Comment by wiiv** [comment]
Sure!
From IC2, "QuantumSuit Bodyarmor".
From Thaumcraft, "Thaumaturge's Robe" and "Void Thaumaturge Robe".

**Comment by thislooksfun** [comment]
Ok, we'll look into it when we have time. Thanks!

**Comment by Funwayguy** [comment]
Screenshots would be nice if possible

**Comment by wiiv** [comment]
With Enviromine:
http://imgur.com/W0lrCSB
Without:
http://imgur.com/j4fOa5l

**Comment by thislooksfun** [comment]
Is this with any EnviroMine items in the inventory, or just with it installed at all?

**Comment by wiiv** [comment]
With it installed.

**Comment by thislooksfun** [comment]
Odd...

**Comment by wiiv** [comment]
Have you figured out the problem? :) It persists in the new release.

**Comment by Funwayguy** [comment]
@wiiv we will let you know if we find/change anything relating to this issue. At the moment we have a fair few other things to work on and not all updates can fix everyone's problems in one go.

**Comment by wiiv** [comment]
Hello, you can dismiss this issue as since version 101, this problem no longer occurs! Thank you!

**Comment by thislooksfun** [comment]
Awesome!
